import util
import time
import pyautogui

# Find dragon on screen
dragon = pyautogui.locateOnScreen('dragon.png')

print('Dragon Position:', dragon)

dragonX = dragon[0]
dragonY = dragon[1]
pyautogui.click((dragonX, dragonY))

t = 0.1

time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
time.sleep(t)
pyautogui.press(' ')
